KyoS.Web/Models/TCMNoteViewModel.cs
using KyoS.Web.Data.Entities;
using System;
using System.Collections.Generic;

namespace KyoS.Web.Models
{
    public class TCMNoteViewModel : TCMNoteEntity
    {
        public int IdCaseManager { get; set; }
        public int IdTCMClient { get; set; }
        public int IdTCMNote { get; set; }

        public int TotalMinutes { get; set; }
        public int TotalUnits { get; set; }
        //este campo lo uso para saber de que pagina se viene
        public int Origin { get; set; }
        public IEnumerable<TCMNoteActivityTempEntity> TCMNoteActivityTemp { get; set; }
        public bool SignSupervisor { get; set; }

        public bool Billable { get; set; }

        public DateTime DateOfServiceReference { get; set; }
    }
}

KyoS.Web/Controllers/TCMNotesController.cs
using KyoS.Common.Enums;
using KyoS.Web.Data;
using KyoS.Web.Data.Entities;
using KyoS.Web.Helpers;
using KyoS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace KyoS.Web.Controllers
{
    public class TCMNotesController : Controller
    {
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;
        private readonly IImageHelper _imageHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IDateHelper _dateHelper;
        private readonly ITranslateHelper _translateHelper;
        private readonly IWebHostEnvironment _webhostEnvironment;
        private readonly IReportHelper _reportHelper;
        private readonly IRenderHelper _renderHelper;

        public TCMNotesController(DataContext context, ICombosHelper combosHelper, IConverterHelper converterHelper, IDateHelper dateHelper, ITranslateHelper translateHelper, IWebHostEnvironment webHostEnvironment, IImageHelper imageHelper, IReportHelper reportHelper, IRenderHelper renderHelper)
        {
            _context = context;
            _combosHelper = combosHelper;
            _converterHelper = converterHelper;
            _dateHelper = dateHelper;
            _translateHelper = translateHelper;
            _webhostEnvironment = webHostEnvironment;
            _imageHelper = imageHelper;
            _reportHelper = reportHelper;
            _renderHelper = renderHelper;
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        }

        [Authorize(Roles = "CaseManager")]
        public async Task<IActionResult> Index(int id = 0)
        {
            if (id == 1)
            {
                ViewBag.FinishEdition = "Y";
            }


            UserEntity user_logged = _context.Users

                                             .Include(u => u.Clinic)
                                             .ThenInclude(c => c.Setting)

                                             .FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (user_logged.Clinic == null || user_logged.Clinic.Setting == null || !user_logged.Clinic.Setting.TCMClinic)
            {
                return RedirectToAction("NotAuthorized", "Account");
            }

            return View(await _context.Weeks
                                      .Include(w => w.Days)
                                      .Include(w => w.Days)
                                      .Include(w => w.Days)

                                      .Where(w => (w.Clinic.Id == user_logged.Clinic.Id
                                                && w.Days.Where(d => (d.Service == ServiceType.PSR)).Count() > 0))
                                      .ToListAsync());
        }

        [Authorize(Roles = "CaseManager, TCMSupervisor, Manager")]
        public async Task<IActionResult> TCMNotesForCase(int idTCMClient = 0, int origin = 0)
        {
            UserEntity user_logged = _context.Users

                                             .Include(u => u.Clinic)
                                             .ThenInclude(c => c.Setting)

                                             .FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (user_logged.Clinic == null || user_logged.Clinic.Setting == null || !user_logged.Clinic.Setting.TCMClinic)
            {
                return RedirectToAction("NotAuthorized", "Account");
            }

            if (User.IsInRole("CaseManager"))
            {
                ViewData["IdTCMClient"] = idTCMClient;
                ViewData["IdCaseManager"] = _context.CaseManagers.FirstOrDefault(n => n.LinkedUser == user_logged.UserName).Id;
                ViewData["origin"] = origin;
                List<TCMNoteEntity> TcmNoteEntity = await _context.TCMNote
                                                                  .Include(w => w.TCMClient)
                                                                  .ThenInclude(d => d.Client)
                                                                  .Include(w => w.TCMNoteActivity)
                                                                  .ThenInclude(d => d.TCMDomain)
                                                                  .Include(w => w.TCMClient)
                                                                  .ThenInclude(d => d.Casemanager)
                                                                  .Where(w => (w.TCMClient.Client.Clinic.Id == user_logged.Clinic.Id
                                                                    && w.TCMClient.Id == idTCMClient))
                                                                  .OrderBy(m => m.DateOfService)
                                                                  .ToListAsync();
                return View(TcmNoteEntity);
            }
            else
            {
                ViewData["IdTCMClient"] = idTCMClient;
                ViewData["IdCaseManager"] = 0;
                ViewData["origin"] = origin;
                List<TCMNoteEntity> TcmNoteEntity = await _context.TCMNote
                                                                  .Include(w => w.TCMClient)
                                                                  .ThenInclude(d => d.Client)
                                                                  .Include(w => w.TCMNoteActivity)
                                                                  .ThenInclude(d => d.TCMDomain)
                                                                  .Include(w => w.TCMClient)
                                                                  .ThenInclude(d => d.Casemanager)
                                                                  .Where(w => (w.TCMClient.Client.Clinic.Id == user_logged.Clinic.Id
                                                                    && w.TCMClient.Id == idTCMClient))
                                                                  .OrderBy(m => m.DateOfService)
                                                                  .ToListAsync();
                return View(TcmNoteEntity);
            }

        }

        [Authorize(Roles = "CaseManager")]
        public IActionResult Create(DateTime dateTime, int IdTCMClient, int origin = 0, bool billable = true)
        {

            UserEntity user_logged = _context.Users
                                             .Include(u => u.Clinic)
                                             .ThenInclude(u => u.Setting)
                                             .FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (_context.TCMDateBlocked.Any(n => n.DateBlocked.Date == dateTime.Date) == true)
            {
                return RedirectToAction("Index", "TCMBilling", new { id = 1});
            }

            //No permite hacer notas si paso 30 dias de la ultima nota y si no tiene ningun AppendixJ despues de eso, siempre que este acvtivo en los setti
            if (user_logged.Clinic.Setting.LockTCMNoteForOneMonthIdle == true)
            {
                List<TCMNoteEntity> list = _context.TCMNote.Where(n => n.TCMClient.Id == IdTCMClient).ToList();
                if (list.Count() > 0)
                {
                    DateTime lastTime = list.MaxBy(n => n.DateOfService).DateOfService;
                    TCMIntakeAppendixJEntity appendixJ = _context.TCMIntakeAppendixJ.FirstOrDefault(n => n.TcmClient_FK == IdTCMClient && n.Date > lastTime);

                    if (lastTime.AddDays(30.0) < dateTime && appendixJ == null)
                    {
                        return RedirectToAction("Index", "TCMBilling", new { id = 3 });
                    }
                }                
            }
            //No permite hacer notas si paso sino tiene una Auth. y un Dx, siempre que este acvtivo en los setting
            if (user_logged.Clinic.Setting.LockTCMNoteForDx == true || user_logged.Clinic.Setting.LockTCMNoteForAuth == true)
            {
                TCMClientEntity tcmClient = _context.TCMClient
                                                    .Include(n => n.Client)
                                                    .ThenInclude(n => n.Clients_Diagnostics)
                                                    .Include(n => n.Client)
                                                    .ThenInclude(n => n.Clients_HealthInsurances)
                                                    .FirstOrDefault(n => n.Id == IdTCMClient);

                if (tcmClient.Client.Clients_Diagnostics.Where(n => n.Principal == true && n.Active == true).Count() == 0)
                {
                    return RedirectToAction("Index", "TCMBilling", new { id = 4 });
                }
                if (tcmClient.Client.Clients_HealthInsurances.Where(n => n.Active == true && n.ApprovedDate.Date < dateTime && n.ExpiredDate.Date > dateTime).Count() == 0)
                {
                    return RedirectToAction("Index", "TCMBilling", new { id = 5 });
                }
            }


            CaseMannagerEntity caseManager = _context.CaseManagers
                                                     .FirstOrDefault(cm => cm.LinkedUser == user_logged.UserName);

            TCMNoteViewModel model;

            if (User.IsInRole("CaseManager"))
            {
                TCMNoteEntity note = _context.TCMNote.FirstOrDefault(n => n.TCMClient.Id == IdTCMClient && n.DateOfService.Date == dateTime.Date);
                if (note == null)
                {

                    model = new TCMNoteViewModel
                    {
                        CreatedBy = user_logged.UserName,

KyoS.Web/Views/TCMNotes/AddMessageEntity.cshtml
@model KyoS.Web.Models.TCMMessageViewModel
@{
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="AddMessageEntity">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdTCMNote" />
            <input type="hidden" asp-for="Origin" />
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Text" class="control-label"></label>
                    <textarea asp-for="Text" class="form-control" rows="4" />
                    <span asp-validation-for="Text" class="text-danger"></span>
                </div>
            </div>
            <div>
                <div class="col-md-offset-9">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
    //    jQueryAjaxPost = form => {
    //        try {
    //            $.ajax({
    //                type: 'POST',
    //                url: form.action,
    //                data: new FormData(form),
    //                contentType: false,
    //                processData: false,
    //                success: function (res) {
    //                    if (res.isValid) {
    //                        $('#view-all').html(res.html)
    //                        $('#form-modal .modal-body').html('');
    //                        $('#form-modal .modal-title').html('');
    //                        $('#form-modal').modal('hide');
    //                    }
    //                    else
    //                        $('#form-modal .modal-body').html(res.html);
    //                },
    //                error: function (err) {
    //                    console.log(err)
    //                }
    //            })
    //            //to prevent default form submit event
    //            return false;
    //        } catch (ex) {
    //            console.log(ex)
    //        }
    //}
    </script>
}

KyoS.Web/Views/TCMNotes/CreateNoteActivityTemp.cshtml
@model KyoS.Web.Models.TCMNoteActivityViewModel
@{
    Layout = null;
}
<div class="row">
    <form asp-action="CreateNoteActivityTemp" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPostTCMNoteActivityTemp(this);">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="CreatedOn" />
        <input type="hidden" asp-for="CreatedBy" />
        <input type="hidden" asp-for="Setting" />
        <input type="hidden" asp-for="IdTCMClient" />
        <input type="hidden" asp-for="DateOfServiceNote" />
        <div class="col-md-push-12">
            <div class="col-md-4">
                &nbsp;
            </div>
            <div class="col-md-4">
                <input type="checkbox" asp-for="Billable" class="form-check-input" readonly id="check1"> Billable
            </div>
           
            <div class="col-md-4">
                &nbsp;
            </div>
        </div>
        <div class="col-md-push-12">
            <div class="col-md-12">
               <hr />
            </div>
        </div>
        <div>
            <div class=" col-md-3 form-group">
                <label asp-for="StartTime" class="control-label">Start Time</label>&nbsp;*
                <input asp-for="StartTime" class="form-control" id="Time_Start" onchange="getMinute();" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-2 form-group">
                <label asp-for="Minutes" class="control-label">Minutes</label>
                <input asp-for="Minutes" id="lbMinutes" class="form-control" onchange="getMinute();" />
                <span asp-validation-for="Minutes" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-2 form-group">
                <label asp-for="TimeEnd" class="control-label">End Time</label>
                <textarea asp-for="TimeEnd" id="lbTimeEnd" class="form-control" rows="1" readonly></textarea>
                <span asp-validation-for="TimeEnd" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-2 form-group">
                <label asp-for="Units" class="control-label">Units</label>
                <textarea asp-for="Units" id="lbUnits" class="form-control" rows="1" readonly></textarea>
                <span asp-validation-for="Units" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-3 form-group">
                <label asp-for="IdSetting" class="control-label"></label>&nbsp;*
                <select asp-for="IdSetting" asp-items="Model.SettingList" class="form-control"></select>
                <span asp-validation-for="IdSetting" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-6 form-group">
                <label asp-for="IdTCMDomain" class="control-label"></label>&nbsp;*
                <select asp-for="IdTCMDomain" asp-items="Model.DomainList" class="form-control" id="cbDomain"></select>
                <span asp-validation-for="IdTCMDomain" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-6 form-group">
                <label asp-for="IdTCMActivity" class="control-label"></label>&nbsp;*
                <select asp-for="IdTCMActivity" asp-items="Model.ActivityList" class="form-control" id="cbActivities"></select>
                <span asp-validation-for="IdTCMActivity" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-12 form-group">
                <label asp-for="SubService" class="control-label">Sub-Service in domain selected</label>
                <textarea asp-for="SubService" class="form-control" rows="1" readonly id="cbSubService"></textarea>
                <span asp-validation-for="SubService" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-12 form-group">
                <label asp-for="NeedIdentified" class="control-label">Need Identified in domain selected</label>
                <textarea asp-for="NeedIdentified" class="form-control" rows="2" readonly id="cbNeed"></textarea>
                <span asp-validation-for="NeedIdentified" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-12 form-group">
                <label asp-for="DescriptionTemp" class="control-label">Activity suggestion</label>
                <textarea asp-for="DescriptionTemp" class="form-control" rows="2" readonly id="Description"></textarea>
                <span asp-validation-for="DescriptionTemp" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-12 form-group">
                <label asp-for="ServiceName" class="control-label">Name of service(s) &nbsp;*</label>
                <textarea asp-for="ServiceName" class="form-control" rows="1"></textarea>
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class=" col-md-12 form-group">
                <label asp-for="DescriptionOfService" class="control-label">Description of service(s) &nbsp;*</label>
                <textarea asp-for="DescriptionOfService" class="form-control" rows="6"></textarea>
                <span asp-validation-for="DescriptionOfService" class="text-danger"></span>
            </div>
        </div>
        <div>
            <div class="col-md-offset-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                &nbsp;
                <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
            </div>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script type="text/javascript">
   
    function getMinute() {
            var url = "@Url.Action("CalcularDateEnd", "TCMNotes")";
        $.get(url, { start: $("#Time_Start").val(), minutes: $("#lbMinutes").val() }, function (data) { $("#lbTimeEnd").text(data); });
              url = "@Url.Action("CalcularUnits", "TCMNotes")";
        $.get(url, { start: $("#Time_Start").val(), minutes: $("#lbMinutes").val() }, function (data) { $("#lbUnits").text(data); });
    }

    function getActivity() {
            var url = "@Url.Action("CalcularMinutes", "TCMNotes")";
            $.get(url, { codeDomain: $("#GetCode").val() }, function (data) { $("#lblDomain").text(data); });
    }

    $("#cbDomain").change(function () {
        var url = "@Url.Action("GetListActivity", "TCMNotes")";
        $.get(url, { idDomain: $("#cbDomain").val() }, function (data) {
            $("#cbActivities").empty();
            $.each(data, function (index, row) {
                $("#cbActivities").append("<option value='" + row.value + "'>" + row.text + "</option>")
            });

              url = "@Url.Action("GetSubService", "TCMServices")";
            $.get(url, { idDomain: $("#cbDomain").val() }, function (data) { $("#cbSubService").text(data); });

             url = "@Url.Action("GetNeedIdentified", "TCMNotes")";
            $.get(url, { idDomain: $("#cbDomain").val() }, function (data) { $("#cbNeed").text(data); });

            //actualizo el label con la sugerencia de la actividad
            url = "@Url.Action("GetSuggestion", "TCMNotes")";
            $.get(url, { idActivity: $("#cbActivities").val() }, function (data) {
                $("#Description").text(data);
            });
        });
    })

    $("#cbActivities").change(function () {
        var url = "@Url.Action("GetSuggestion", "TCMNotes")";
            $.get(url, { idActivity: $("#cbActivities").val() }, function (data) {
                $("#Description").text(data);
            });
    })

</script>

KyoS.Web/Views/TCMNotes/EditReadOnly.cshtml
@model KyoS.Web.Models.TCMNoteViewModel
@{
    ViewData["Title"] = "TCM Notes";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>

    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @if (ViewData["origi"].ToString() == "1")
                {
                    @Html.ActionLink("Pending Notes", "NotesStatus", "TCMNotes", new { status = KyoS.Common.Enums.NoteStatus.Pending })
                }
                @if (ViewData["origi"].ToString() == "2")
                {
                    @Html.ActionLink("TCM Notes with review", "NotesWithReview", "TCMNotes")
                }
                @if (ViewData["origi"].ToString() == "3")
                {
                    @Html.ActionLink("TCM Notifications", "Notifications", "TCMMessages")
                }
                @if (ViewData["origi"].ToString() == "4")
                {
                    @Html.ActionLink("Billing", "TCMSupervisor", "TCMBilling")
                }
            </li>
            <li class="active">TCM Notes</li>
        </ul><!--.breadcrumb-->
    </div>


    <div class="row">
        <form asp-action="EditReadOnly" asp-route-id="@Model.Id" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdTCMClient" />
            <input type="hidden" asp-for="IdTCMNote" />
            <input type="hidden" asp-for="TCMClient.Casemanager.Name" />
            <input type="hidden" asp-for="CreatedOn" />
            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="Origin" />
            <partial name="_TCMNotes" />
            <div class="col-md-push-12">
                <div id="view-NoteActivity">
                    @await Html.PartialAsync("_ViewTCMNoteActivity", Model.TCMNoteActivity.ToList(), new ViewDataDictionary(ViewData) { { "Id", @ViewData["available"] } })
                </div>
            </div>
            <partial name="_TCMNotes1ReadOnly" />
            <div class="form-group col-md-12">
                @if (User.IsInRole("TCMSupervisor"))
                {
                    <input type="submit" value="Approve" asp-route-id="@Model.Id" asp-route-origi="@ViewData["origi"]" class="btn btn-primary" />
                    @*<a asp-action="ApprovedNote" asp-route-id="@Model.Id" asp-route-origin="@ViewData["origi"]" asp-route-model="@Model" class="btn btn-primary">Approve</a>*@
                    <a class="btn btn-warning" onclick="showInPopup('@Url.Action("AddMessageEntity","TCMNotes",new {id = Model.Id, origi = @ViewData["origi"]},Context.Request.Scheme)','Add message to casemanager')" title="Not approved note due to problems">Review</a>
                }
                @if (ViewData["origi"].ToString() == "1")
                {
                    <a asp-action="NotesStatus" asp-route-status="@KyoS.Common.Enums.NoteStatus.Pending" class="btn btn-success">Back</a>
                }
                @if (ViewData["origi"].ToString() == "2")
                {
                    <a asp-action="NotesWithReview" class="btn btn-success">Back</a>
                }
                @if (ViewData["origi"].ToString() == "3")
                {
                    <a asp-action="Notifications" asp-controller="TCMMessages" class="btn btn-success">Back</a>
                }
                @if (ViewData["origi"].ToString() == "4")
                {
                    <a asp-action="TCMSupervisor" asp-controller="TCMBilling" class="btn btn-success">Back</a>
                }
            </div>
        </form>
    </div>
</body>
</html>

<partial name="_ModalPopupLg" />
<partial name="_ModalPopup" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">

    </script>
}

KyoS.Web/Views/TCMNotes/Search.cshtml
@model KyoS.Web.Models.TCMServiceNoteViewModel
@{
    ViewData["Title"] = "TCM Notes";
}

<link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Dashboard", "Index", "Desktop")
        </li>
        <li class="active">PSR Notes</li>
    </ul><!--.breadcrumb-->
</div>

<div class="row">
    <form asp-action="Search" enctype="multipart/form-data">
        <div class="form-group col-md-12">
            <div class="col-md-4">
                <label asp-for="IdTCMService" class="control-label">Domain</label>
                <select asp-for="IdTCMService" asp-items="Model.TCMServices" class="form-control" id="cbService"></select>
               
            </div>
            <div class="col-md-3">
                <label asp-for="IdTCMActivity" class="control-label"></label>
                <select asp-for="IdTCMActivity" asp-items="Model.TCMServicesActivity" class="form-control" id="cbActivity"></select>
               
            </div>
            <td align="right">
                <br />
                <input type="submit" value="Filter" class="btn btn-success" />
            </td>
        </div>
    </form>
    <div class="col-md-12">
        <hr />
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Notes by Activities (@Model.TCMNoteActivities.Count())</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-responsive table-striped" id="MyTable">
                    <thead>
                        <tr>
                            <th class="col-md-2">
                                Name of service(s)
                            </th>
                            <th class="col-md-2"  style="text-align:left;">
                                CMH
                            </th>
                            <th class="col-md-7">
                                Description of service(s)
                            </th>
                            <th class="col-md-2" style="text-align:center;">
                                Minutes
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.TCMNoteActivities)
                        {
                            <tr>
                                <td >
                                    @item.ServiceName
                                </td>
                                <td>
                                    @item.TCMNote.TCMClient.Casemanager.Name
                                </td>
                                <td>
                                    @item.DescriptionOfService
                                </td>
                                <td align="center">
                                    @item.Minutes
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<partial name="_ModalPopup" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/moment.min.js"></script>
    <script src="~/js/datetime-moment.js"></script>

    <script type="text/javascript">

        $(document).ready(function () {
            $("#cbService").change(function () {
                var url = "@Url.Action("GetActivityByService", "TCMNotes")";
                $.get(url, { idService: $("#cbService").val() }, function (data) {
                    $("#cbActivity").empty();
                    $.each(data, function (index, row) {
                        $("#cbActivity").append("<option value='" + row.value + "'>" + row.text + "</option>")
                    });

                   
                });
            })
            $('#MyTable').DataTable({
                "order": [[3, "asc"]],
                "pageLength": 100
            });
                         
          

           
        });


    </script>
}