KyoS.Web/Models/FarsFormViewModel.cs
using KyoS.Web.Data.Entities;
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace KyoS.Web.Models
{
    public class FarsFormViewModel : FarsFormEntity
    {
        [Display(Name = "Client")]
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a Client.")]

        public int IdClient { get; set; }
        public int IdSupervisor { get; set; }
        public int Origin { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Type")]
        [Range(0, int.MaxValue, ErrorMessage = "You must select a Type.")]
        public int IdType { get; set; }
        public IEnumerable<SelectListItem> FarsType { get; set; }
    }
}

KyoS.Web/Controllers/FarsFormsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KyoS.Web.Data;
using KyoS.Web.Data.Entities;
using KyoS.Web.Helpers;
using KyoS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;
using KyoS.Common.Enums;
using KyoS.Common.Helpers;

namespace KyoS.Web.Controllers
{
    public class FarsFormsController : Controller
    {
        private readonly IUserHelper _userHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IRenderHelper _renderHelper;
        private readonly IReportHelper _reportHelper;
        private readonly DataContext _context;
        private readonly IOverlapindHelper _overlapingHelper;

        public FarsFormsController(IUserHelper userHelper, IConverterHelper converterHelper, ICombosHelper combosHelper, IRenderHelper renderHelper, DataContext context, IReportHelper reportHelper, IOverlapindHelper overlapingHelper)
        {
            _userHelper = userHelper;
            _combosHelper = combosHelper;
            _context = context;
            _renderHelper = renderHelper;
            _converterHelper = converterHelper;
            _reportHelper = reportHelper;
            _overlapingHelper = overlapingHelper;
        }

        [Authorize(Roles = "Manager, Supervisor, Facilitator, Documents_Assistant, Frontdesk")]
        public async Task<IActionResult> Index(int idError = 0)
        {
            if (idError == 1) //Imposible to delete
            {
                ViewBag.Delete = "N";
            }

            UserEntity user_logged = await _context.Users

                                                   .Include(u => u.Clinic)
                                                   .ThenInclude(c => c.Setting)
                                                   
                                                   .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (user_logged.Clinic == null || user_logged.Clinic.Setting == null || !user_logged.Clinic.Setting.MentalHealthClinic)
            {
                return RedirectToAction("NotAuthorized", "Account");
            }
            else
            {
                FacilitatorEntity facilitator = _context.Facilitators.FirstOrDefault(n => n.LinkedUser == user_logged.UserName);
                if (User.IsInRole("Manager")|| User.IsInRole("Supervisor") || User.IsInRole("Frontdesk"))
                    return View(await _context.Clients

                                              .Include(f => f.FarsFormList)

                                              .Where(n => n.Clinic.Id == user_logged.Clinic.Id)
                                              .OrderBy(f => f.Name)
                                              .ToListAsync());

                if (User.IsInRole("Documents_Assistant"))
                    return View(await _context.Clients

                                              .Include(f => f.FarsFormList)

                                              .Where(n => n.Clinic.Id == user_logged.Clinic.Id && n.FarsFormList.Where(m => m.CreatedBy == user_logged.UserName).Count()>0)
                                              .OrderBy(f => f.Name)
                                              .ToListAsync());

                if (User.IsInRole("Facilitator"))
                {
                    return View(await _context.Clients

                                              .Include(f => f.FarsFormList)

                                              .Where(n => n.Clinic.Id == user_logged.Clinic.Id
                                                && (n.IdFacilitatorPSR == facilitator.Id || n.IndividualTherapyFacilitator.Id == facilitator.Id || n.IdFacilitatorGroup == facilitator.Id))
                                              .OrderBy(f => f.Name)
                                              .ToListAsync());
                }
            }
            return RedirectToAction("NotAuthorized", "Account");
        }

        [Authorize(Roles = "Supervisor, Facilitator, Documents_Assistant")]
        public IActionResult Create(int id = 0, int origin = 0)
        {

            UserEntity user_logged = _context.Users
                                             .Include(u => u.Clinic)
                                             .FirstOrDefault(u => u.UserName == User.Identity.Name);
            ClientEntity client = _context.Clients.Include(n => n.FarsFormList)
                                                  .Include(n => n.Clinic)
                                                  .FirstOrDefault(n => n.Id == id);
            FarsFormViewModel model;

            if (user_logged.Clinic != null)
            {
                model = new FarsFormViewModel
                {
                   IdClient = id,
                   Client = client,
                   Id = 0,
                   AbilityScale = 0,
                   AdmissionedFor = user_logged.FullName,
                   ActivitiesScale = 0,
                   AnxietyScale = 0,
                   CognitiveScale = 0,
                   ContractorID = client.Clinic.ProviderMedicaidId,
                   Country = "13",
                   DangerToOtherScale = 0,
                   DangerToSelfScale = 0,
                   DcfEvaluation = "",
                   DepressionScale = 0,
                   EvaluationDate = DateTime.Now,
                   FamilyEnvironmentScale = 0,
                   FamilyRelationShipsScale = 0,
                   HyperAffectScale = 0,
                   InterpersonalScale = 0,
                   MCOID = "",
                   MedicaidProviderID = client.Clinic.ProviderTaxId,
                   MedicaidRecipientID = client.MedicaidID,
                   MedicalScale = 0,
                   M_GafScore = "",
                   ProviderId = client.Clinic.ProviderTaxId,
                   ProviderLocal = client.Clinic.Address + ", " + client.Clinic.City + ", " + client.Clinic.State + ", "+ client.Clinic.ZipCode,
                   RaterEducation = "",
                   RaterFMHI = "",
                   SecurityScale = 0,
                   SignatureDate = DateTime.Now,
                   SocialScale = 0,
                   SubstanceAbusoHistory = 0,
                   SubstanceScale = 0,
                   ThoughtProcessScale = 0,
                   TraumaticsScale = 0,
                   WorkScale = 0,
                     
                   ContID1 = client.Clinic.ProviderTaxId,
                   ContID2 = "",
                   ContID3 = "",
                   ProgramEvaluation = "",
                   Status = FarsStatus.Edition,
                   IdSupervisor = 0,
                   Supervisor = new SupervisorEntity(),
                   IdType = 0,
                   FarsType = _combosHelper.GetComboFARSType(),
                   StartTime = DateTime.Now,
                   EndTime = DateTime.Now.AddMinutes(15),
                   CodeBill = user_logged.Clinic.CodeFARS
                };

                SupervisorEntity supervisor = _context.Supervisors.FirstOrDefault(n => n.LinkedUser == user_logged.UserName);
                if (User.IsInRole("Supervisor") && supervisor != null)
                {
                    model.Supervisor = supervisor;
                    model.IdSupervisor = supervisor.Id;
                    model.RaterEducation = supervisor.RaterEducation;
                    model.RaterFMHI = supervisor.RaterFMHCertification;
                }

                DocumentsAssistantEntity documentsAssistant = _context.DocumentsAssistant.FirstOrDefault(n => n.LinkedUser == user_logged.UserName);
                if (User.IsInRole("Documents_Assistant") && documentsAssistant != null)
                {
                    model.RaterEducation = documentsAssistant.RaterEducation;
                    model.RaterFMHI = documentsAssistant.RaterFMHCertification;
                }

                FacilitatorEntity facilitator = _context.Facilitators.FirstOrDefault(n => n.LinkedUser == user_logged.UserName);
                if (User.IsInRole("Facilitator") && facilitator != null)
                {
                    model.RaterEducation = facilitator.RaterEducation;
                    model.RaterFMHI = facilitator.RaterFMHCertification;
                }

                if (model.Client.FarsFormList == null)
                    model.Client.FarsFormList = new List<FarsFormEntity>();
                ViewData["Origin"] = origin;
                return View(model);
                }
            
            return RedirectToAction("NotAuthorized", "Account");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Supervisor, Facilitator, Documents_Assistant")]
        public async Task<IActionResult> Create(FarsFormViewModel FarsFormViewModel, int origin = 0)
        {
            UserEntity user_logged = _context.Users
                                             .Include(u => u.Clinic)
                                             .FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (ModelState.IsValid)
            {
                FarsFormEntity farsFormEntity = _context.FarsForm.Find(FarsFormViewModel.Id);
                if (farsFormEntity == null)
                {
                    //calcular las unidades a partir del tiempo de desarrollo del FARS
                    int units = (FarsFormViewModel.EndTime.TimeOfDay - FarsFormViewModel.StartTime.TimeOfDay).Minutes / 15;
                    if ((FarsFormViewModel.EndTime.TimeOfDay - FarsFormViewModel.StartTime.TimeOfDay).Minutes % 15 > 7)
                    {
                        units++;
                        FarsFormViewModel.Units = units;
                    }

KyoS.Web/Views/FarsForms/AddMessageEntity.cshtml
@model KyoS.Web.Models.MessageViewModel
@{
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="AddMessageEntity">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdFarsForm" />
            <input type="hidden" asp-for="Origin" />
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Text" class="control-label"></label>
                    <textarea asp-for="Text" class="form-control" rows="4" />
                    <span asp-validation-for="Text" class="text-danger"></span>
                </div>
            </div>
            <div>
                <div class="col-md-offset-9">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>   
}

KyoS.Web/Views/FarsForms/ClientswithoutFARS.cshtml
@model IEnumerable<KyoS.Web.Data.Entities.ClientEntity>
@{
    ViewData["Title"] = "Clients without FARS";
}

@if (Model != null)
{
<link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Dashboard", "Index", "Desktop")
        </li>
        <li class="active">Clients without FARS</li>
    </ul><!--.breadcrumb-->
</div>

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Clients without FARS</h3>
        </div>
        <div class="panel-body" id="view-ClientsWithoutBIO">
            <table class="table table-hover table-responsive table-striped" id="MyTable">
                <thead>
                    <tr>
                        <th class="col-md-3">
                            Client Name
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            Admission Date
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            Client Status
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            FARS (amount)
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            Missing
                        </th>
                        <th class="col-md-1" style="text-align:center;">

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                     {
                        <tr>
                            <td>
                                @if (item.Gender == KyoS.Common.Enums.GenderType.Female)
                                {
                                    <i class="glyphicon glyphicon-user btn-danger"></i>
                                }
                                @if (item.Gender == KyoS.Common.Enums.GenderType.Male)
                                {
                                    <i class="glyphicon glyphicon-user btn-primary"></i>
                                }
                                &nbsp;
                                @Html.DisplayFor(modelItem => item.Name)
                                |
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.AdmisionDate)
                            </td>
                            <td align="center">
                                @if (item.Status == KyoS.Common.Enums.StatusType.Open)
                                 {
                                     <span class="label label-success">
                                        Open
                                     </span>
                                 }
                                @if (item.Status == KyoS.Common.Enums.StatusType.Close)
                                 {
                                    <span class="label label-default">
                                        Close
                                    </span>
                                 }
                            </td>
                            <td align="center">
                                @if (item.FarsFormList.Count() > 0)
                                {
                                    @item.FarsFormList.Count()
                                }

                            </td>
                            <td align="center">
                                <a onclick="showInPopupLg('@Url.Action("AuditFARSforId", "FarsForms", new { id = @item.Id }, Context.Request.Scheme)','Audit FARS')" class="btn btn-info" title="Audit FARS"><i class="glyphicon glyphicon-search"></i></a>
                            </td>
                            <td align="right">

                                @if (User.IsInRole("Facilitator") || User.IsInRole("Documents_Assistant"))
                                {
                                    <a asp-action="Create" asp-controller="FarsForms" asp-route-id="@item.Id" asp-route-origin="2" class="btn btn-primary" title="Create FARS"><i class="glyphicon glyphicon-plus"></i></a>
                                }
                                else
                                {
                                    <a class="btn btn-primary disabled" title="Create FARS"><i class="glyphicon glyphicon-plus"></i></a>
                                }
                            </td>
                        </tr>
                     }
                </tbody>
            </table>
        </div>
    </div>
</div>

}
<partial name="_ModalPopupLg" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $('#MyTable').DataTable({
               "pageLength": 100
            });

            // Delete item
            //var item_to_delete;

            @*$('.deleteItem').click((e) => {
                item_to_delete = e.currentTarget.dataset.id;
            });

            $("#btnYesDelete").click(function () {
                var url = "@Url.Action("Delete", "WorkDays")";
                window.location.href = url + '/' + item_to_delete;
            });*@
        });
    </script>
}

KyoS.Web/Views/FarsForms/Create.cshtml
@model KyoS.Web.Models.FarsFormViewModel
@{
    ViewData["Title"] = "Create Fars Form";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />    
</head>
<body>

    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @if (ViewData["Origin"].ToString() == "0")
                {
                    @Html.ActionLink("Index", "Index", "FarsForms")
                }
                @if (ViewData["Origin"].ToString() == "1")
                {
                    @Html.ActionLink("Clients without initial FARS", "ClientswithoutInitialFARS", "FarsForms")
                }
                @if (ViewData["Origin"].ToString() == "2")
                {
                    @Html.ActionLink("Clients without FARS", "ClientswithoutFARS", "FarsForms")
                }
            </li>
            <li class="active">Create Fars Form</li>
        </ul><!--.breadcrumb-->
    </div>

    <h4>Create Fars Form</h4>
    <hr />
    <div class="row">       
        <form asp-action="Create" asp-route-id="@Model.Id" asp-route-origin="@ViewData["Origin"]" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdClient" />
            <input type="hidden" asp-for="AdmissionedFor" />
            <input type="hidden" asp-for="Status" />
            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="CreatedOn" />
            <input type="hidden" asp-for="LastModifiedBy" />
            <input type="hidden" asp-for="LastModifiedOn" />
            <input type="hidden" asp-for="Client.FirstName" />
            <input type="hidden" asp-for="Client.LastName" />
            <partial name="_FarsForms" />
            <div class="form-group col-md-12">
                <input type="submit" value="Create" class="btn btn-primary" />
                @if (ViewData["Origin"].ToString() == "0")
                {
                    <a asp-action="Index" class="btn btn-success">Back</a>
                }
                @if (ViewData["Origin"].ToString() == "1")
                {
                    <a asp-action="ClientswithoutInitialFARS" class="btn btn-success">Back</a>
                }
                @if (ViewData["Origin"].ToString() == "2")
                {
                    <a asp-action="ClientswithoutFARS" class="btn btn-success">Back</a>
                }
            </div>
        </form>       
    </div>
</body>
</html>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">

    </script>
}

KyoS.Web/Views/FarsForms/Edit.cshtml
@model KyoS.Web.Models.FarsFormViewModel
@{
    ViewData["Title"] = "Edit Fars Form";
}


<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @if (Model.Origin == 0)
            {
                @Html.ActionLink("Fars Forms", "Index", "FarsForms")
            }
            @if (Model.Origin == 1)
            {
                @Html.ActionLink("Pending Fars Forms", "PendingFars", "FarsForms")
            }
            @if (Model.Origin == 2)
            {
                @Html.ActionLink("Messages", "MessagesOfFars", "Messages")
            }
            @if (Model.Origin == 3)
            {
                @Html.ActionLink("Notifications", "Notifications", "Messages")
            }
            @if (Model.Origin == 4)
            {
                @Html.ActionLink("Edition Fars Forms", "Editionfars", "FarsForms")
            }
            @if (Model.Origin == 5)
            {
                @Html.ActionLink("Documents Assistant CMH Calendar", "IndexDocumentsAssistant", "Calendar")
            }
        </li>
        <li class="active">Edit Fars Form</li>
    </ul><!--.breadcrumb-->
</div>

<h4>Edit Fars Form</h4>
<hr />
<div class="row">        
    <form asp-action="Edit" asp-route-id="@Model.Id" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="IdClient" />
        <input type="hidden" asp-for="AdmissionedFor" />
        <input type="hidden" asp-for="Status" />
        <input type="hidden" asp-for="CreatedBy" />
        <input type="hidden" asp-for="CreatedOn" />
        <input type="hidden" asp-for="LastModifiedBy" />
        <input type="hidden" asp-for="LastModifiedOn" />
        <input type="hidden" asp-for="Origin" />
        <input type="hidden" asp-for="Client.FirstName" />
        <input type="hidden" asp-for="Client.LastName" />
        <partial name="_FarsForms" />
        <div class="form-group col-md-12">
            <input type="submit" value="Save All" class="btn btn-primary" title="Save it and back" />
            @if (User.IsInRole("Supervisor"))
            {
                <a class="btn btn-warning" onclick="showInPopup('@Url.Action("AddMessageEntity","FarsForms",new {id = Model.Id, origin = Model.Origin},Context.Request.Scheme)','Add message to document creator')" title="Not approved note due to problems">Review</a>
                <a asp-action="ApproveFars" asp-route-id="@Model.Id" class="btn btn-default" title="Approve FARS">Approve</a>
            }
            @if (Model.Origin == 0)
            {
                <a asp-action="Index" class="btn btn-success">Back</a>
            }
            @if (Model.Origin == 1)
            {
                <a asp-action="PendingFars" class="btn btn-success">Back</a>
            }
            @if (Model.Origin == 2)
            {
                <a asp-action="MessagesOfFars" asp-controller="Messages" class="btn btn-success">Back</a>
            }
            @if (Model.Origin == 3)
            {
                <a asp-action="Notifications" asp-controller="Messages" class="btn btn-success">Back</a>
            }
            @if (Model.Origin == 4)
            {
                <a asp-action="EditionFars" class="btn btn-success">Back</a>
            }
            @if (Model.Origin == 5)
            {
                <a asp-action="IndexDocumentsAssistant" asp-controller="Calendar" class="btn btn-success">Back</a>
            }
        </div>
    </form>        
</div>

<partial name="_ModalPopup" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}       
}

KyoS.Web/Views/FarsForms/FARSMissingForClient.cshtml
@model IEnumerable<KyoS.Web.Data.Entities.ClientEntity>
@{
    ViewData["Title"] = "Clients without FARS";
}

@if (Model != null)
{
<link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Dashboard", "Index", "Desktop")
        </li>
        <li class="active">Clients without FARS</li>
    </ul><!--.breadcrumb-->
</div>

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Clients without FARS</h3>
        </div>
        <div class="panel-body" id="view-ClientsWithoutBIO">
            <table class="table table-hover table-responsive table-striped" id="MyTable">
                <thead>
                    <tr>
                        <th class="col-md-3">
                            Client Name
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            Client Code
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            Admission Date
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            Client Status
                        </th>
                        <th class="col-md-2" style="text-align:center;">
                            Services
                        </th>
                        <th class="col-md-1" style="text-align:center;">

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                     {
                        <tr>
                            <td>
                                @if (item.Gender == KyoS.Common.Enums.GenderType.Female)
                                        {
                                <i class="glyphicon glyphicon-user btn-danger"></i>
                                        }
                                @if (item.Gender == KyoS.Common.Enums.GenderType.Male)
                                        {
                                <i class="glyphicon glyphicon-user btn-primary"></i>
                                        }
                                &nbsp;
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.AdmisionDate)
                            </td>
                            <td align="center">
                                @if (item.Status == KyoS.Common.Enums.StatusType.Open)
                                 {
                                     <span class="label label-success">
                                    Open
                                </span>
                                 }
                                @if (item.Status == KyoS.Common.Enums.StatusType.Close)
                                 {
                                    <span class="label label-default">
                                        Close
                                    </span>
                                 }
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Service)
                            </td>
                            <td align="right">
                                <a onclick="showInPopupLg('@Url.Action("AuditFARSforId", "FarsForms", new { id = @item.Id }, Context.Request.Scheme)','Audit FARS')" class="btn btn-info" title="Audit FARS"><i class="glyphicon glyphicon-search"></i>&nbsp;&nbsp;</a>
                            </td>
                        </tr>
                     }
                </tbody>
            </table>
        </div>
    </div>
</div>

}

<partial name="_ModalPopupLg" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $('#MyTable').DataTable({
               "pageLength": 100
            });

            // Delete item
            //var item_to_delete;

            @*$('.deleteItem').click((e) => {
                item_to_delete = e.currentTarget.dataset.id;
            });

            $("#btnYesDelete").click(function () {
                var url = "@Url.Action("Delete", "WorkDays")";
                window.location.href = url + '/' + item_to_delete;
            });*@
        });
    </script>
}