KyoS.Web/Models/CaseMannagerViewModel.cs
using KyoS.Web.Data.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KyoS.Web.Models
{
    public class CaseMannagerViewModel:CaseMannagerEntity
    {
        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Clinic")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a clinic.")]
        public int IdClinic { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Status")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a status.")]
        public int IdStatus { get; set; }

        [Display(Name = "Linked user")]
        public string IdUser { get; set; }

        [Display(Name = "Signature")]
        public IFormFile SignatureFile { get; set; }

        public IEnumerable<SelectListItem> UserList { get; set; }

        public IEnumerable<SelectListItem> StatusList { get; set; }

        public IEnumerable<SelectListItem> Clinics { get; set; }

      
        [Display(Name = "TCM Supervisor")]
        public int IdTCMsupervisor { get; set; }

        public IEnumerable<SelectListItem> TCMsupervisors { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Gender")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a gender.")]
        public int IdGender { get; set; }
        public IEnumerable<SelectListItem> GenderList { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Payment Methods")]
        [Range(0, int.MaxValue, ErrorMessage = "You must select a payment method.")]
        public int IdPaymentMethod { get; set; }
        public IEnumerable<SelectListItem> PaymentMethodList { get; set; }

        [Required(ErrorMessage = "The field {0} is mandatory.")]
        [Display(Name = "Account Type")]
        [Range(0, int.MaxValue, ErrorMessage = "You must select a account type.")]
        public int IdAccountType { get; set; }
        public IEnumerable<SelectListItem> AccountTypeList { get; set; }

        public List<CaseManagerCertificationEntity> CaseManagerCertificationIdealList { get; set; }
    }
}

KyoS.Web/Controllers/CaseMannagerController.cs
using KyoS.Common.Enums;
using KyoS.Web.Data;
using KyoS.Web.Data.Entities;
using KyoS.Web.Helpers;
using KyoS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using KyoS.Web.Migrations;
using KyoS.Common.Helpers;

namespace KyoS.Web.Controllers
{
    public class CaseMannagerController : Controller
    {
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IImageHelper _imageHelper;
        private readonly IRenderHelper _renderHelper;

        public CaseMannagerController(DataContext context, ICombosHelper combosHelper, IConverterHelper converterHelper, IImageHelper imageHelper, IRenderHelper renderHelper)
        {
            _context = context;
            _combosHelper = combosHelper;
            _converterHelper = converterHelper;
            _imageHelper = imageHelper;
            _renderHelper = renderHelper;
        }

        [Authorize(Roles = "Manager, TCMSupervisor, CaseManager")]
        public async Task<IActionResult> Index(int idError = 0)
        {
            UserEntity user_logged = await _context.Users

                                                  .Include(u => u.Clinic)
                                                  .ThenInclude(c => c.Setting)

                                                  .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (user_logged.Clinic == null || user_logged.Clinic.Setting == null || !user_logged.Clinic.Setting.TCMClinic)
            {
                return RedirectToAction("NotAuthorized", "Account");
            }

            if (idError == 1) //Imposible to delete
            {
                ViewBag.Delete = "N";
            }

            if (User.IsInRole("Manager"))
            {
               
                ClinicEntity clinic = await _context.Clinics.FirstOrDefaultAsync(c => c.Id == user_logged.Clinic.Id);
                if (clinic != null)
                    return View(await _context.CaseManagers
                                              .Include(f => f.Clinic)
                                              .Include(f => f.TCMSupervisor)
                                              .Include(f => f.TCMClients)
                                              .ThenInclude(f => f.Client)
                                              .Include(f => f.TCMCertifications)
                                              .Where(f => f.Clinic.Id == clinic.Id).OrderBy(f => f.Name).ToListAsync());
               
            }
            else
            {
                if (User.IsInRole("TCMSupervisor"))
                {
                    TCMSupervisorEntity supervisorEntity = _context.TCMSupervisors.FirstOrDefault(n => n.LinkedUser == user_logged.UserName);

                    return View(await _context.CaseManagers
                                              .Include(f => f.Clinic)
                                              .Include(f => f.TCMSupervisor)
                                              .Include(f => f.TCMClients)
                                              .ThenInclude(f => f.Client)
                                              .Include(f => f.TCMCertifications)
                                              .Where(f => f.Clinic.Id == user_logged.Clinic.Id
                                                       && f.TCMSupervisor.Id == supervisorEntity.Id)
                                              .OrderBy(f => f.Name).ToListAsync());

                }
                else
                {
                    if (User.IsInRole("CaseManager"))
                    {
                        CaseMannagerEntity casemanagerEntity = _context.CaseManagers.FirstOrDefault(n => n.LinkedUser == user_logged.UserName);

                        return View(await _context.CaseManagers
                                                  .Include(f => f.Clinic)
                                                  .Include(f => f.TCMSupervisor)
                                                  .Include(f => f.TCMClients)
                                                  .ThenInclude(f => f.Client)
                                                  .Include(f => f.TCMCertifications)
                                                  .Where(f => f.Clinic.Id == user_logged.Clinic.Id
                                                           && f.Id == casemanagerEntity.Id)
                                                  .OrderBy(f => f.Name).ToListAsync());

                    }
                }
            }
            return null;
        }

        [Authorize(Roles = "Manager")]
        public IActionResult Create(int id = 0)
        {
            if (id == 1)
            {
                ViewBag.Creado = "Y";
            }
            else
            {
                if (id == 2)
                {
                    ViewBag.Creado = "E";
                }
                else
                {
                    ViewBag.Creado = "N";
                }
            }

            CaseMannagerViewModel model;

            if (User.IsInRole("Manager"))
            {
                UserEntity user_logged = _context.Users.Include(u => u.Clinic)
                                                             .FirstOrDefault(u => u.UserName == User.Identity.Name);
                if (user_logged.Clinic != null)
                {
                    ClinicEntity clinic = _context.Clinics.FirstOrDefault(c => c.Id == user_logged.Clinic.Id);
                    List<SelectListItem> list = new List<SelectListItem>();
                    list.Insert(0, new SelectListItem
                    {
                        Text = clinic.Name,
                        Value = $"{clinic.Id}"
                    });
                    model = new CaseMannagerViewModel
                    {
                        Clinics = list,
                        IdClinic = clinic.Id,
                        StatusList = _combosHelper.GetComboClientStatus(),
                        UserList = _combosHelper.GetComboUserNamesByRolesClinic(UserType.CaseManager, user_logged.Clinic.Id),
                        Money = 0,
                        IdTCMsupervisor = 0,
                        TCMsupervisors = _combosHelper.GetComboTCMSupervisorByClinic(user_logged.Clinic.Id),
                        IdGender = 0,
                        GenderList = _combosHelper.GetComboGender(),
                        IdAccountType = 0,
                        AccountTypeList = _combosHelper.GetComboAccountType()

                    };
                    return View(model);
                }
            }

            model = new CaseMannagerViewModel
            {
                Clinics = _combosHelper.GetComboClinics(),
                IdStatus = 1,
                StatusList = _combosHelper.GetComboClientStatus(),
                UserList = _combosHelper.GetComboUserNamesByRolesClinic(UserType.CaseManager, 0),
                Money = 0,
                IdTCMsupervisor = 0,
                TCMsupervisors = _combosHelper.GetComboTCMSupervisorByClinic(0)
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Create(CaseMannagerViewModel caseMannagerViewModel)
        {
            if (ModelState.IsValid)
            {
                CaseMannagerEntity casemannager = await _context.CaseManagers.FirstOrDefaultAsync(f => f.Name == caseMannagerViewModel.Name);
                if (casemannager == null)
                {
                    if (caseMannagerViewModel.IdUser == "0")
                    {
                        ModelState.AddModelError(string.Empty, "You must select a linked user");
                        return View(caseMannagerViewModel);
                    }

                    string path = string.Empty;
                    if (caseMannagerViewModel.SignatureFile != null)
                    {
                        path = await _imageHelper.UploadImageAsync(caseMannagerViewModel.SignatureFile, "Signatures");
                    }
                    CaseMannagerEntity caseMannagerEntity = await _converterHelper.ToCaseMannagerEntity(caseMannagerViewModel, path, true);

                    _context.Add(caseMannagerEntity);
                    try
                    {
                        await _context.SaveChangesAsync();
                        return RedirectToAction("Create", new { id = 1 });
                    }
                    catch (System.Exception ex)
                    {
                        if (ex.InnerException.Message.Contains("duplicate"))
                        {
                            ModelState.AddModelError(string.Empty, $"Already exists the Case Mannager: {caseMannagerEntity.Name}");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                        }
                    }
                }
                else
                {
                    return RedirectToAction("Create", new { id = 2 });
                }
            }
            return View(caseMannagerViewModel);
        }

        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Home/Error404");
            }

            CaseMannagerEntity caseMannagerEntity = await _context.CaseManagers.FirstOrDefaultAsync(t => t.Id == id);
            if (caseMannagerEntity == null)
            {

KyoS.Web/Views/CaseMannager/CaseManagerCertification.cshtml
@model IEnumerable<KyoS.Web.Data.Entities.CaseManagerCertificationEntity>
@{
    ViewData["Title"] = "Case Managers";
}

<link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Case Managers", "Index", "CaseMannager")
        </li>
        <li class="active">Certifications</li>
    </ul><!--.breadcrumb-->
</div>

<p>
    @if (User.IsInRole("Manager"))
    {
        <a onclick="showInPopup('@Url.Action("CreatCaseManagerCertification","CaseMannager",null,Context.Request.Scheme)','Add Certification')" class="btn btn-primary" title="Add Certification"><i class="glyphicon glyphicon-plus"></i> Add Certification</a>
    }    
    <a onclick="showInPopupLg('@Url.Action("AuditCertification","CaseMannager",null,Context.Request.Scheme)','Audit TCM Certifications')" class="btn btn-danger" title="Audit TCM Certifications"><i class="glyphicon glyphicon-alert"></i>  Audit TCM Certifications</a>
</p>

<div class="row">
    <div class="col-md-12">
        @if (ViewBag.Delete == "N")
        {
            <div class="alert alert-block alert-danger">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="icon-remove"></i>
                </button>
                <strong class="red">
                    Error. It is not posible delete the case manager
                </strong>
            </div>
        }
    </div>
</div>

<div class="row">
    <div id="view-casemanagerCertification">
        @await Html.PartialAsync("_ViewCaseManagerCertifications", Model)
    </div>
</div>
<partial name="_ModalPopup" />
<partial name="_ModalPopupLg" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                "order": [[1, "asc"]],
                "pageLength": 50
            });
        });
        function ConfirmDelete(e) {
            Swal.fire({
                title: 'Do you want to delete?',
                text: "Note: All data related to this element will be deleted.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    var url = "@Url.Action("DeleteCertification", "CaseMannager")";
                    window.location.href = url + '/' + e;
                }
            });
        }
      
    </script>
}

KyoS.Web/Views/CaseMannager/Create.cshtml
@model KyoS.Web.Models.CaseMannagerViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @Html.ActionLink("Case Managers", "Index", "CaseMannager")
            </li>
            <li class="active">Create</li>
        </ul><!--.breadcrumb-->
    </div>

    <h4>Create new case manager</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            @if (ViewBag.Creado == "Y")
            {
                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <i class="icon-ok green"></i>
                    <strong class="green">
                        Case Manager been successfully created
                    </strong>

                </div>
            }
            @if (ViewBag.Creado == "E")
            {
                <div class="alert alert-block alert-warning">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <i class="icon-ok red"></i>
                    <strong class="red">
                        Error. Case Manager already exist
                    </strong>
                </div>
            }
        </div>
        <div>
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <partial name="_CaseMannager" />
                <div class="form-group col-md-12">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-success">Back</a>
                </div>
            </form>
        </div>
    </div>

</body>
</html>

KyoS.Web/Views/CaseMannager/CreateModal.cshtml
@model KyoS.Web.Models.CaseMannagerViewModel
@{
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="CreateModal" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPostCaseManagers(this);">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#personal" aria-controls="personal" role="tab" data-toggle="tab">Personal</a></li>
                <li role="presentation"><a href="#agency" aria-controls="agency" role="tab" data-toggle="tab">Agency</a></li>
                <li role="presentation"><a href="#private" aria-controls="private" role="tab" data-toggle="tab">Private</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="personal">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IdClinic" />
                    <input type="hidden" asp-for="Name" />
                    <partial name="_Personal" />
                    <div class="form-group col-md-12">
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="agency">
                    <partial name="_Agency" />
                </div>
                <div role="tabpanel" class="tab-pane" id="private">
                    <partial name="_Private" />
                </div>
            </div>
            <div class="col-md-12">
                <div form-group">
                    <hr />
                </div>
            </div>
            <div>
                <div class="col-md-offset-9 form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>

KyoS.Web/Views/CaseMannager/Edit.cshtml
@model KyoS.Web.Models.CaseMannagerViewModel
@{
    ViewData["Title"] = "Edit";
}

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Case Managers", "Index", "CaseMannager")
        </li>
        <li class="active">Edit</li>
    </ul><!--.breadcrumb-->
</div>
<h4>Edit case manager</h4>
<hr />
<div class="row">
    <div>
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="SignaturePath" />
            <partial name="_CaseMannager" />
            <div class="col-md-4">
                @if (!string.IsNullOrEmpty(Model.SignaturePath))
                {
                    <img src="@Url.Content(Model.SignaturePath)" alt="Image" style="width:200px;height:100px;max-width: 100%; height: auto;" />
                }
            </div>
            <div class="col-md-12">
                &nbsp;
            </div>
            <div class="form-group col-md-12">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-success">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KyoS.Web/Views/CaseMannager/Index.cshtml
@model IEnumerable<KyoS.Web.Data.Entities.CaseMannagerEntity>
@{
    ViewData["Title"] = "Case Managers";
}

<link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Dashboard", "Index", "Desktop")
        </li>
        <li class="active">Case Managers</li>
    </ul><!--.breadcrumb-->
</div>

<p>
    @if (User.IsInRole("Manager"))
    {
        <a onclick="showInPopupLg('@Url.Action("CreateModal","CaseMannager",null,Context.Request.Scheme)','Create Case Manager')" class="btn btn-primary" title="Create Case Manager"><i class="glyphicon glyphicon-plus"></i> Create Case Manager</a>
        <a asp-action="Signatures" class="btn btn-default"><i class="glyphicon glyphicon-pencil"></i> Case Manager's Signatures</a>
    }        
    <a asp-action="CaseManagerCertification" class="btn btn-default"><i class="glyphicon glyphicon-eye-open"></i> Case Manager's certifications</a>
    <a onclick="showInPopupLg('@Url.Action("AuditCertification","CaseMannager",null,Context.Request.Scheme)','Audit TCM Certifications')" class="btn btn-danger" title="Audit TCM Certifications"><i class="glyphicon glyphicon-alert"></i>  Audit TCM Certifications</a>
</p>

<div class="row">
    <div class="col-md-12">
        @if (ViewBag.Delete == "N")
        {
            <div class="alert alert-block alert-danger">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="icon-remove"></i>
                </button>
                <strong class="red">
                    Error. It is not posible delete the case manager
                </strong>
            </div>
        }
    </div>
</div>

<div class="row">
    <div id="view-casemanagers">
        @await Html.PartialAsync("_ViewCaseManagers", Model.ToList())
    </div>
</div>

<partial name="_ModalPopupLg" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                "order": [[1, "asc"]],
                "pageLength": 50
            });            
        });

        function ConfirmDelete(e) {
            Swal.fire({
                title: 'Do you want to delete?',
                text: "Note: All data related to this element will be deleted.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    var url = "@Url.Action("Delete", "CaseMannager")";
                    window.location.href = url + '/' + e;
                }
            });
        }
        $(function () {

            //Assign Click event to Plus Image.
            $("body").on("click", "a[class*='icon-plus-sign-alt']", function () {
                $(this).closest("tr").after("<tr><td></td><td colspan = '999'>" + $(this).next().html() + "</td></tr>");
                $(this).attr("class", "icon-minus-sign-alt");
            });
            //Assign Click event to Minus Image.
            $("body").on("click", "a[class*='icon-minus-sign-alt']", function () {
                $(this).attr("class", "icon-plus-sign-alt");
                $(this).closest("tr").next().remove();
            });
        });
    </script>
}

KyoS.Web/Views/CaseMannager/_Private.cshtml
@model KyoS.Web.Models.CaseMannagerViewModel
<div class="col-md-push-12">
    &nbsp;
</div>

<div>
    <div class="col-md-3 form-group">
        <label asp-for="NPI" class="control-label"></label>
        <input asp-for="NPI" class="form-control" />
        <span asp-validation-for="NPI" class="text-danger"></span>
    </div>
    <div class="col-md-3 form-group">
        <label asp-for="SSN" class="control-label"></label>
        <input asp-for="SSN" class="form-control" />
        <span asp-validation-for="SSN" class="text-danger"></span>
    </div>
    <div class="col-md-3 form-group">
        <label asp-for="CompanyName" class="control-label"> Company Name</label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger"></span>
    </div>
    <div class="col-md-3 form-group">
        <label asp-for="CompanyEIN" class="control-label"> Company EIN</label>
        <input asp-for="CompanyEIN" class="form-control" />
        <span asp-validation-for="CompanyEIN" class="text-danger"></span>
    </div>
    <div class="col-md-4 form-group">
        <label asp-for="FinancialInstitutionsName" class="control-label">Bank Name</label>
        <input asp-for="FinancialInstitutionsName" class="form-control" />
        <span asp-validation-for="FinancialInstitutionsName" class="text-danger"></span>
    </div>
   <div class="col-md-4 form-group">
        <label asp-for="IdAccountType" class="control-label"></label>
        <select asp-for="IdAccountType" asp-items="Model.AccountTypeList" class="form-control"></select>
        <span asp-validation-for="IdAccountType" class="text-danger"></span>
    </div>
    <div class="col-md-2 form-group">
        <label asp-for="AccountNumber" class="control-label">Account Number</label>
        <input asp-for="AccountNumber" class="form-control" />
        <span asp-validation-for="AccountNumber" class="text-danger"></span>
    </div>
    <div class="col-md-2 form-group">
        <label asp-for="Routing" class="control-label"></label>
        <input asp-for="Routing" class="form-control" />
        <span asp-validation-for="Routing" class="text-danger"></span>
    </div>
   
</div>

<div class="col-md-push-12">
    &nbsp;
</div>

KyoS.Web/Views/CaseMannager/_ViewCaseManagerCertifications.cshtml
@model IEnumerable<KyoS.Web.Data.Entities.CaseManagerCertificationEntity>

@if (Model != null)
{
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Case Managers Certifications</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover table-responsive table-striped" id="MyTable">
                <thead>
                    <tr>
                        <th class="col-md-3">
                            TCM
                        </th>
                        <th class="col-md-3" style="text-align:center;">
                            Course
                        </th>
                        <th class="col-md-1" style="text-align:center;">
                            Number
                        </th>
                        <th class="col-md-1" style="text-align:center;">
                           Date
                        </th>
                        <th class="col-md-1" style="text-align:center;">
                            Expirate
                        </th>
                        <th class="col-md-1" style="text-align:center;">
                            TCM Active
                        </th>
                        <th class="col-md-2">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                            <tr style="color: darkgrey;">
                                <td>
                                    @Html.DisplayFor(modelItem => item.TCM.Name)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.CertificationNumber)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.CertificateDate)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.ExpirationDate)
                                </td>
                                <td align="center">
                                    @if (item.TCM.Status == KyoS.Common.Enums.StatusType.Open)
                                    {
                                        <span class="label label-success">
                                            Open
                                        </span>
                                    }
                                    @if (item.TCM.Status == KyoS.Common.Enums.StatusType.Close)
                                    {
                                        <span class="label label-default">
                                            Close
                                        </span>
                                    }
                                </td>
                                <td align="right">
                                    @if (User.IsInRole("Manager"))
                                    {
                                        <a onclick="showInPopup('@Url.Action("EditCaseManagerCertification","CaseMannager",new {id = @item.Id},Context.Request.Scheme)','Edit TCMCertification')" class="btn btn-warning" title="Edit TCM Certification"><i class="glyphicon glyphicon-pencil"></i></a>
                                        <button onclick="ConfirmDelete(@item.Id)" class="btn btn-danger deleteItem" title="Delete TCM Certification"><i class="glyphicon glyphicon-trash"></i></button>
                                    }
                                    else
                                    {
                                        <a onclick="showInPopup('@Url.Action("EditCaseManagerCertification","CaseMannager",new {id = @item.Id},Context.Request.Scheme)','Edit TCMCertification')" class="btn btn-warning disabled" title="Edit TCM Certification"><i class="glyphicon glyphicon-pencil"></i></a>
                                        <button onclick="ConfirmDelete(@item.Id)" class="btn btn-danger deleteItem disabled" title="Delete TCM Certification"><i class="glyphicon glyphicon-trash"></i></button>
                                    }

                                </td>
                            </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
}