KyoS.Web/Models/IncidentReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KyoS.Web.Data.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace KyoS.Web.Models
{
    public class IncidentReportViewModel : IncidentReportEntity
    {
        [Display(Name = "Client")]
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a Client.")]

        public int IdClient { get; set; }
        public int IdFacilitator { get; set; }
        public int IdSupervisor { get; set; }
        public int IdDocumentAssisstant { get; set; }

        public IEnumerable<SelectListItem> Clients { get; set; }
    }
}

KyoS.Web/Controllers/IncidentReportController.cs
using KyoS.Web.Data;
using KyoS.Web.Data.Entities;
using KyoS.Web.Helpers;
using KyoS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace KyoS.Web.Controllers
{
    public class IncidentReportController : Controller
    {
        private readonly IUserHelper _userHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IRenderHelper _renderHelper;
        private readonly IReportHelper _reportHelper;
        private readonly DataContext _context;

        public IncidentReportController(IUserHelper userHelper, IConverterHelper converterHelper, ICombosHelper combosHelper, IRenderHelper renderHelper, DataContext context, IReportHelper reportHelper)
        {
            _userHelper = userHelper;
            _combosHelper = combosHelper;
            _context = context;
            _renderHelper = renderHelper;
            _converterHelper = converterHelper;
            _reportHelper = reportHelper;
        }

        [Authorize(Roles = "Manager, Supervisor, Facilitator, Frontdesk, Documents_Assistant")]
        public async Task<IActionResult> Index(int idError = 0)
        {
            if (idError == 1) //Imposible to delete
            {
                ViewBag.Delete = "N";
            }

            UserEntity user_logged = await _context.Users
                                                   .Include(u => u.Clinic)
                                                   .ThenInclude(c => c.Setting)
                                                   .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (user_logged.Clinic == null || user_logged.Clinic.Setting == null || !user_logged.Clinic.Setting.MentalHealthClinic)
            {
                return RedirectToAction("NotAuthorized", "Account");
            }
            else
            {
                if (User.IsInRole("Manager") || User.IsInRole("Supervisor") || User.IsInRole("Frontdesk"))
                    return View(await _context.Clients

                                              .Include(f => f.IncidentReport)
                                              .Include(f => f.Clinic)
                                              .ThenInclude(f => f.Setting)

                                              .Where(n => n.Clinic.Id == user_logged.Clinic.Id
                                                       && n.IncidentReport.Count() > 0)
                                              .OrderBy(f => f.Name)
                                              .ToListAsync());

                if (User.IsInRole("Facilitator"))
                {
                    FacilitatorEntity facilitator = _context.Facilitators.FirstOrDefault(n => n.LinkedUser == user_logged.UserName);

                    List<ClientEntity> clientList = await _context.Clients
                                                                  .Include(f => f.IncidentReport)
                                                                  .Include(f => f.Clinic)
                                                                  .ThenInclude(f => f.Setting)
                                                                  .Where(n => (n.IdFacilitatorGroup == facilitator.Id
                                                                           || n.IdFacilitatorPSR == facilitator.Id
                                                                           || n.IndividualTherapyFacilitator.Id == facilitator.Id)
                                                                           && n.IncidentReport.Count() > 0)
                                                                  .OrderBy(f => f.Name)
                                                                  .ToListAsync();

                    return View(clientList);
                }
                if (User.IsInRole("Documents_Assistant"))
                {
                    DocumentsAssistantEntity documentAssisstant = _context.DocumentsAssistant
                                                                          .FirstOrDefault(n => n.LinkedUser == user_logged.UserName);

                    List<ClientEntity> clientList = await _context.Clients
                                                                  .Include(f => f.IncidentReport)
                                                                  .Include(f => f.Clinic)
                                                                  .ThenInclude(f => f.Setting)
                                                                  .Where(n => (n.Bio.DocumentsAssistant.Id == documentAssisstant.Id
                                                                            || n.IncidentReport.Where(m => m.DocumentAssisstant.Id == documentAssisstant.Id).Count() > 0)
                                                                           && n.IncidentReport.Count() > 0)
                                                                  .OrderBy(f => f.Name)
                                                                  .ToListAsync();

                    return View(clientList);
                }
            }
            return RedirectToAction("NotAuthorized", "Account");
        }

        [Authorize(Roles = "Facilitator, Documents_Assistant, Supervisor")]
        public IActionResult Create(int idClient = 0)
        {

            UserEntity user_logged = _context.Users
                                             .Include(u => u.Clinic)
                                             .ThenInclude(u => u.Setting)
                                             .FirstOrDefault(u => u.UserName == User.Identity.Name);

            IncidentReportViewModel model = new IncidentReportViewModel();
            ClientEntity client = _context.Clients
                                          .FirstOrDefault(n => n.Id == idClient);

            if (User.IsInRole("Facilitator"))
            {
                FacilitatorEntity facilitator = _context.Facilitators
                                                        .FirstOrDefault(n => n.LinkedUser == user_logged.UserName);
                if (user_logged.Clinic != null)
                {
                    model = new IncidentReportViewModel
                    {
                        IdClient = idClient,
                        Clients = _combosHelper.GetComboActiveClientsByClinic(user_logged.Clinic.Id),
                        Client = client,
                        Id = 0,
                        Facilitator = facilitator,
                        IdFacilitator = facilitator.Id,
                        CreatedBy = user_logged.UserName,
                        CreatedOn = DateTime.Today,
                        AdmissionFor = user_logged.FullName,
                        DateIncident = DateTime.Today,
                        DateReport = DateTime.Today,
                        DateSignatureEmployee = DateTime.Today,
                        DescriptionIncident = string.Empty,
                        IdDocumentAssisstant = 0,
                        IdSupervisor = 0,
                        Injured = false,
                        Injured_Description = string.Empty,
                        Location = string.Empty,
                        TimeIncident = DateTime.Today,
                        Witnesses = false,
                        Witnesses_Contact = string.Empty

                    };

                    return View(model);
                }
            }
            if (User.IsInRole("Documents_Assistant"))
            {
                DocumentsAssistantEntity documentsAssistant = _context.DocumentsAssistant
                                                                      .FirstOrDefault(n => n.LinkedUser == user_logged.UserName);
                if (user_logged.Clinic != null)
                {
                    model = new IncidentReportViewModel
                    {
                        IdClient = idClient,
                        Client = client,
                        Id = 0,
                        IdFacilitator = 0,
                        CreatedBy = user_logged.UserName,
                        CreatedOn = DateTime.Today,
                        DocumentAssisstant = documentsAssistant,
                        IdDocumentAssisstant = documentsAssistant.Id,
                        AdmissionFor = user_logged.FullName,
                        DateIncident = DateTime.Today,
                        DateReport = DateTime.Today,
                        DateSignatureEmployee = DateTime.Today,
                        DescriptionIncident = string.Empty,
                        IdSupervisor = 0,
                        Injured = false,
                        Injured_Description = string.Empty,
                        Location = string.Empty,
                        Supervisor = new SupervisorEntity(),
                        TimeIncident = DateTime.Today,
                        Witnesses = false,
                        Witnesses_Contact = string.Empty

                    };

                    return View(model);
                }
            }
            if (User.IsInRole("Supervisor"))
            {
                SupervisorEntity supervisor = _context.Supervisors
                                                      .FirstOrDefault(n => n.LinkedUser == user_logged.UserName);
                if (user_logged.Clinic != null)
                {
                    model = new IncidentReportViewModel
                    {
                        IdClient = idClient,
                        Clients = _combosHelper.GetComboActiveClientsByClinic(user_logged.Clinic.Id),
                        Client = client,
                        Id = 0,
                        IdFacilitator = 0,

KyoS.Web/Views/IncidentReport/Create.cshtml
@model KyoS.Web.Models.IncidentReportViewModel
@{
    ViewData["Title"] = "Create Incident";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>

    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @Html.ActionLink("All Incident Report", "Index", "IncidentReport")
            </li>
            <li class="active">Create Incident Report</li>
        </ul><!--.breadcrumb-->
    </div>

    <h4>Create Incident Report</h4>
    <hr />
    <div class="row">
        <form asp-action="Create" asp-route-id="@Model.Id" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdClient" />
            <input type="hidden" asp-for="IdFacilitator" />
            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="CreatedOn" />
            <input type="hidden" asp-for="AdmissionFor" />
            <input type="hidden" asp-for="IdSupervisor" />
            <input type="hidden" asp-for="IdDocumentAssisstant" />

            <partial name="_IncidentReport" />
            <div class="form-group col-md-12">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" asp-controller="IncidentReport" class="btn btn-success">Back</a>
            </div>
        </form>
    </div>
</body>
</html>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">

    </script>
}

KyoS.Web/Views/IncidentReport/Edit.cshtml
@model KyoS.Web.Models.IncidentReportViewModel
@{
    ViewData["Title"] = "Edit Incident";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>

    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @Html.ActionLink("All Incident Report", "Index", "Incident Report")
            </li>
            <li class="active">Edit Incident Report</li>
        </ul><!--.breadcrumb-->
    </div>

    <h4>Edit Incident Report</h4>
    <hr />
    <div class="row">
        <form asp-action="Edit" asp-route-id="@Model.Id" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdClient" />
            <input type="hidden" asp-for="IdFacilitator" />
            <input type="hidden" asp-for="IdDocumentAssisstant" />
            <input type="hidden" asp-for="IdSupervisor" />
            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="CreatedOn" />
            <input type="hidden" asp-for="AdmissionFor" />

            <partial name="_IncidentReport" />
            <div class="form-group col-md-12">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" asp-controller="IncidentReport" class="btn btn-success">Back</a>
            </div>
        </form>
    </div>
</body>
</html>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">

    </script>
}

KyoS.Web/Views/IncidentReport/EditReadOnly.cshtml
@model KyoS.Web.Models.IncidentReportViewModel
@{
    ViewData["Title"] = "Incident Report";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>

    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home"></i>
                @Html.ActionLink("All Incident Report", "Index", "IncidentReport")
            </li>
            <li class="active">Incident Report</li>
        </ul><!--.breadcrumb-->
    </div>

    <h4>Incident Report</h4>
    <hr />
    <div class="row">
        <form asp-action="EditReadOnly" asp-route-id="@Model.Id" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdClient" />
            <input type="hidden" asp-for="IdFacilitator" />
            <input type="hidden" asp-for="IdDocumentAssisstant" />
            <input type="hidden" asp-for="IdSupervisor" />
            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="CreatedOn" />

            <partial name="_IncidentReportReadOnly" />
            <div class="form-group col-md-12">
                <a asp-action="Index" asp-controller="IncidentReport" class="btn btn-success">Back</a>
            </div>
        </form>
    </div>
</body>
</html>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>
}

KyoS.Web/Views/IncidentReport/Index.cshtml
@model IEnumerable<KyoS.Web.Data.Entities.ClientEntity>
@{
    ViewData["Title"] = "Incident Reports";
}
<link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />

<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Html.ActionLink("Dashboard", "Index", "Desktop")
        </li>
        <li class="active">All Incident Reports</li>
    </ul><!--.breadcrumb-->
</div>
<div class="row">
    <div class="col-md-12">
        @if (User.IsInRole("Facilitator") || User.IsInRole("Supervisor") || User.IsInRole("Documents_Assistant"))
        {
            <a onclick="showInPopup('@Url.Action("SelectClient", "IncidentReport", Context.Request.Scheme)','Select Client')" class="btn btn-primary" title="Select CLient"><i class="glyphicon glyphicon-plus"></i> Create Incident Report</a>
        }
        else
        {
            <a class="btn btn-primary disabled" title="Select CLient"><i class="glyphicon glyphicon-plus"></i> Create Incident Report</a>
        }
    </div>
    <div class="col-md-12">
        &nbsp;
    </div>
    <div class="col-md-12">
        @if (ViewBag.Delete == "N")
        {
            <div class="alert alert-block alert-danger">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="icon-remove"></i>
                </button>
                <strong class="red">
                    Error. It is not posible delete the Incident Report
                </strong>
            </div>
        }
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Incident Reports</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-responsive table-striped" id="MyTable">
                    <thead>
                        <tr>
                            <th class="col-md-1">
                               
                            </th>
                            <th class="col-md-4">
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th class="col-md-1" style="text-align:center;">
                                @Html.DisplayNameFor(model => model.Code)
                            </th>
                            <th class="col-md-2" style="text-align:center;">
                                Admission Date
                            </th>
                            <th class="col-md-1" style="text-align:center;">
                                Status
                            </th>
                            <th class="col-md-2" style="text-align:center;">
                                MH Therapy
                            </th>
                            <th class="col-md-1" style="text-align:center;">
                                Amount
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td align="center">
                                    @if (item.IncidentReport.Count() != 0)
                                    {
                                        <a class="icon-plus-sign-alt"></a>
                                    }                                    
                                    <div style="display:none">
                                        <table class="table table-striped table-bordered">
                                            <tr>
                                                <th class="col-md-2" style="text-align:center">Reporter</th>
                                                <th class="col-md-1" style="text-align:center">Date</th>
                                                <th class="col-md-7" style="text-align:left">Description</th>
                                                <th class="col-md-2" style="text-align:center"></th>
                                            </tr>
                                            @foreach (var element in item.IncidentReport)
                                            {
                                                <tr>
                                                    <td align="center">@Html.DisplayFor(modelItem => element.AdmissionFor)</td>
                                                    <td align="center">@Html.DisplayFor(modelItem => element.DateIncident)</td>
                                                    <td align="left">@Html.DisplayFor(modelItem => element.DescriptionIncident)</td>
                                                    <td align="center">
                                                        @if (User.Identity.Name == element.CreatedBy)
                                                        {
                                                            <a asp-action="Edit" asp-route-id="@element.Id" class="btn btn-success" title="Edit Incident Report"><i class="glyphicon glyphicon-pencil"></i></a>
                                                            <a class="btn btn-success" asp-action="PrintIncidentReport" asp-route-id="@element.Id" title="Print Incident Report" target="_blank"><i class="glyphicon glyphicon-print"></i></a>
                                                        }
                                                        else
                                                        {
                                                            <a asp-action="EditReadOnly" asp-route-id="@element.Id" class="btn btn-info" title="View Incident Report"><i class="glyphicon glyphicon-search"></i></a>
                                                            <a class="btn btn-success" asp-action="PrintIncidentReport" asp-route-id="@element.Id" title="Print Incident Report" target="_blank"><i class="glyphicon glyphicon-print"></i></a>
                                                        }
                                                    </td>                                               
                                                </tr>                                               
                                            }
                                        </table>
                                    </div>
                                </td>
                                <td>
                                    @if (item.Gender == KyoS.Common.Enums.GenderType.Female)
                                    {
                                        <i class="glyphicon glyphicon-user btn-danger"></i>
                                    }
                                    @if (item.Gender == KyoS.Common.Enums.GenderType.Male)
                                    {
                                        <i class="glyphicon glyphicon-user btn-primary"></i>
                                    }
                                    &nbsp;
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.Code)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.AdmisionDate)
                                </td>
                                <td align="center">
                                    @if (item.Status == KyoS.Common.Enums.StatusType.Open)
                                    {
                                        <span class="label label-success">
                                            Open
                                        </span>
                                    }
                                    @if (item.Status == KyoS.Common.Enums.StatusType.Close)
                                    {
                                        <span class="label label-default">
                                            Close
                                        </span>
                                    }
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.Service)
                                </td>
                                <td align="center">
                                   @item.IncidentReport.Count
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<partial name="_ModalPopup" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
         $(document).ready(function () {
              $('#MyTable').DataTable({
                  "order": [[0, "asc"]],
                   "pageLength": 100
              });

             // Delete item
             var item_to_delete;
             $('.deleteItem').click((e) => {
                 item_to_delete = e.currentTarget.dataset.dataset.id;
             });

             $("#btnYesDelete").click(function () {
             var url = "@Url.Action("Delete", "FarsForms")";
                 window.location.href = url + '/' + item_to_delete;
             });
         });
        $(function () {

            //Assign Click event to Plus Image.
            $("body").on("click", "a[class*='icon-plus-sign-alt']", function () {
                $(this).closest("tr").after("<tr><td></td><td colspan = '999'>" + $(this).next().html() + "</td></tr>");
                $(this).attr("class", "icon-minus-sign-alt");
            });
            //Assign Click event to Minus Image.
            $("body").on("click", "a[class*='icon-minus-sign-alt']", function () {
                $(this).attr("class", "icon-plus-sign-alt");
                $(this).closest("tr").next().remove();
            });
        });
    </script>
}

KyoS.Web/Views/IncidentReport/SelectClient.cshtml
@model KyoS.Web.Models.IncidentReportViewModel
@{
    Layout = null;
}

<div class="row">
    <form asp-action="SelectClient" asp-route-id="@Model.IdClient">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="col-md-8">
            <div class="form-group">
                <label asp-for="IdClient" class="control-label">Client</label>
                <select asp-for="IdClient" asp-items="Model.Clients" class="form-control"></select>
                <span asp-validation-for="IdClient" class="text-danger"></span>
            </div>
        </div>
        <div class="container-fluid">
            &nbsp;
        </div>
        <div class="container-fluid">
            &nbsp;
        </div>
        <div class="col-md-12">
            <div class="col-md-offset-9">
                <input type="submit" value="Select" class="btn btn-primary" />
                <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
            </div>
        </div>
    </form>
</div>